export const turkishWords = [
  "Araba", "Uçak", "Gemi", "Tren", "Bisiklet",
  "Kedi", "Köpek", "Kuş", "Balık", "At",
  "Ev", "Okul", "Hastane", "Pazar", "Kafe",
  "Deniz", "Dağ", "Orman", "Nehir", "Göl",
  "Güneş", "Ay", "Yıldız", "Bulut", "Yağmur",
  "Kitap", "Kalem", "Defter", "Çanta", "Masa",
  "Sandalye", "Dolap", "Yatak", "Kapı", "Pencere",
  "Elma", "Armut", "Portakal", "Muz", "Üzüm",
  "Ekmek", "Su", "Süt", "Çay", "Kahve",
  "Ağaç", "Çiçek", "Yaprak", "Dal", "Kök",
  "Telefon", "Bilgisayar", "Televizyon", "Radyo", "Saat",
  "Gözlük", "Şapka", "Ayakkabı", "Ceket", "Pantolon",
  "Kırmızı", "Mavi", "Yeşil", "Sarı", "Beyaz",
  "Müzik", "Dans", "Şarkı", "Oyun", "Film",
  "Aşk", "Barış", "Dostluk", "Mutluluk", "Özgürlük",
  "Kale", "Köprü", "Yol", "Meydan", "Park",
  "Resim", "Heykel", "Fotoğraf", "Ayna", "Çerçeve",
  "Top", "Kanat", "Zaman", "Rüya", "Ses",
  "Işık", "Gölge", "Renk", "Şekil", "Boyut",
  "Kış", "Yaz", "İlkbahar", "Sonbahar", "Mevsim",
  "Sabah", "Öğle", "Akşam", "Gece", "Gün",
  "Hafta", "Ay", "Yıl", "Asır", "Çağ",
  "Dünya", "Gezegen", "Uzay", "Galaksi", "Evren",
  "Bilim", "Sanat", "Tarih", "Coğrafya", "Matematik",
  "Doktor", "Öğretmen", "Mühendis", "Aşçı", "Şoför",
  "Anne", "Baba", "Kardeş", "Dede", "Nine",
  "Arkadaş", "Komşu", "Misafir", "Yolcu", "İzleyici",
  "Kalp", "Beyin", "Göz", "Kulak", "El",
  "Ayak", "Baş", "Saç", "Diş", "Burun",
  "Pasta", "Börek", "Pilav", "Çorba", "Salata",
  "Kaplan", "Aslan", "Fil", "Zürafa", "Maymun",
  "Karınca", "Arı", "Kelebek", "Örümcek", "Sinek",
  "Gül", "Papatya", "Lale", "Karanfil", "Menekşe",
  "Altın", "Gümüş", "Bronz", "Demir", "Bakır",
  "Taş", "Kum", "Toprak", "Çamur", "Kaya",
  "Kar", "Buz", "Dolu", "Fırtına", "Şimşek",
  "Ada", "Kıta", "Okyanus", "Kanal", "Körfez",
  "Kraliçe", "Kral", "Prens", "Prenses", "Şövalye",
  "Ejderha", "Peri", "Dev", "Cüce", "Büyücü",
  "Kılıç", "Kalkan", "Ok", "Yay", "Mızrak",
  "Taç", "Taht", "Hazine", "Anahtar", "Kilit",
  "Gitar", "Piyano", "Keman", "Davul", "Flüt",
  "Futbol", "Basketbol", "Voleybol", "Tenis", "Yüzme",
  "Bayrak", "Madalya", "Şampiyonluk", "Ödül", "Derece",
  "Harita", "Pusula", "Teleskop", "Mikroskop", "Büyüteç",
  "Roket", "Uydu", "Astronot", "Gezgin", "Kaşif",
  "Şehir", "Kasaba", "Köy", "Mahalle", "Sokak",
  "Kütüphane", "Müze", "Sinema", "Tiyatro", "Opera"
];

// This function is now deprecated - use storage.getRandomGameWords() instead
// Kept for backward compatibility
export function getRandomWords(count: number): string[] {
  const shuffled = [...turkishWords].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, count);
}
