export const turkishWords = [
  "Acı", "Adet", "Afrika", "Ağ", "Ağaç", "Ağız", "Ahtapot", "Ajan", "Akım", "Alay",
  "Albüm", "Alem", "Almanya", "Altın", "Amazon", "Ambulans", "Amerika", "Ana", "Anahtar", "Antartika",
  "Araba", "Arabesk", "Arpacık", "Asker", "Aslan", "Aşçı", "At", "Ateş", "Atlas", "Atlet",
  "Avrupa", "Avukat", "Avustralya", "Ay", "Ayak", "Ayakkabı", "Ayı", "Ayna", "Azrail", "Bağ",
  "Baklava", "Bal", "Balık", "Balina", "Balkon", "Balta", "Banka", "Banko", "Bardak", "Baskı",
  "Baş", "Bayram", "Benzin", "Bere", "Berlin", "Beyaz", "Beyin", "Bıçak", "Bilye", "Bizans",
  "Blok", "Boğaz", "Bomba", "Bot", "Boy", "Bozuk", "Bölüm", "Buz", "Cadı", "Cami",
  "Cep", "Cilt", "Cüce", "Çamaşır", "Çatal", "Çatı", "Çay", "Çekirdek", "Çeyiz", "Çikolata",
  "Çimen", "Çizme", "Çoban", "Dahi", "Daire", "Dalga", "Dalgıç", "Damat", "Dans", "Darbe",
  "Deli", "Delik", "Derece", "Dev", "Devir", "Devlet", "Dinozor", "Diş", "Diyet", "Dizi",
  "Doğru", "Doktor", "Dolu", "Don", "Dondurma", "Döviz", "Dövme", "Duvar", "Düdük", "Düğme",
  "Düğün", "Dümen", "Düş", "Ejderha", "Ekmek", "El", "Elbise", "Eldiven", "Elmas", "Eşkiya",
  "Etiket", "Everest", "Fan", "Far", "Fare", "Fatura", "Faul", "Felek", "Fener", "Festival",
  "Fırça", "Film", "Flüt", "Form", "Füze", "Garaj", "Gaz", "Gazino", "Gece", "Gemi",
  "Gıcık", "Gırgır", "Göbek", "Göç", "Gökdelen", "Gölge", "Göz", "Gulyabani", "Gül", "Gün",
  "Halat", "Hastalık", "Hastane", "Hava", "Havuç", "Havuz", "Hayalet", "Hayat", "Hazine", "Helikopter",
  "Hemşire", "Hesap", "Hırsız", "Hindistan", "Hitit", "Hollywood", "Hortum", "Hücre", "Izgara", "İğne",
  "İngiltere", "İnternet", "İran", "İskele", "İstanbul", "İz", "Jet", "Kabuk", "Kağıt", "Kahraman",
  "Kahve", "Kale", "Kalpazan", "Kamyonet", "Kanal", "Kanat", "Kanepe", "Kanguru", "Kanun", "Kaptan",
  "Kare", "Karınca", "Kart", "Kartal", "Kaset", "Kaş", "Kaval", "Kavurma", "Kaymak", "Kaynak",
  "Kaynana", "Kaza", "Kazık", "Kedi", "Kemer", "Kepçe", "Kepek", "Kese", "Kıbrıs", "Kırbaç",
  "Kısır", "Kitap", "Klasik", "Koca", "Kolon", "Konser", "Konsolosluk", "Kopya", "Korsan", "Kovan",
  "Köpek", "Köprü", "Köstebek", "Köy", "Kral", "Kriz", "Kulaç", "Kule", "Kumarhane", "Kupa",
  "Kupon", "Kurşun", "Kuru", "Kuşak", "Kutu", "Kuvvet", "Kuyruk", "Kuyu", "Küme", "Küpe",
  "Lastik", "Laz", "Lazer", "Limuzin", "Londra", "Macun", "Magazin", "Makam", "Makara", "Makas",
  "Mango", "Mantar", "Mars", "Marş", "Masa", "Maskara", "Mat", "Maya", "Mecnun", "Melek",
  "Memur", "Merkez", "Mevlana", "Mezarcı", "Mezopotamya", "Mezuniyet", "Mısır", "Mikroskop", "Milyoner", "Moda",
  "Mors", "Moskova", "Motor", "Mucize", "Nal", "Nemrut", "Ninja", "Nişan", "Not", "Numara",
  "Ocak", "Omurga", "Opera", "Ordu", "Orman", "Orta", "Otel", "Oyuncak", "Öğretmen", "Ölüm",
  "Örgü", "Örgüt", "Örtü", "Örümcek", "Paça", "Pala", "Palet", "Pamuk", "Paraşüt", "Park",
  "Parmak", "Parti", "Pas", "Pasta", "Pazar", "Pazı", "Pekin", "Penguen", "Perde", "Pike",
  "Piliç", "Pilot", "Piramit", "Pirinç", "Plaj", "Poker", "Polis", "Posta", "Prenses", "Pul",
  "Rejim", "Reklam", "Robot", "Roma", "Rüzgar", "Sahte", "Sandalye", "Sandık", "Satır", "Satürn",
  "Savaş", "Sayfa", "Saz", "Sepet", "Servis", "Set", "Sıra", "Sırt", "Simit", "Site",
  "Soğuk", "Solucan", "Sosyete", "Söz", "Stadyum", "Su", "Survivor", "Şans", "Şerit", "Şişe",
  "Şok", "Şövalye", "Tabanca", "Tablet", "Tablo", "Taht", "Takım", "Tampon", "Tarla", "Tarzan",
  "Taş", "Tavla", "Tavşan", "Teleskop", "Temel", "Terazi", "Tesbih", "Tez", "Tıp", "Tiyatro",
  "Tokyo", "Top", "Topuz", "Torpido", "Torpil", "Tren", "Tulum", "Tur", "Türkçe", "Uçak",
  "Uşak", "Uydu", "Uzaylı", "Ünlü", "Vize", "Yağmur", "Yaka", "Yastık", "Yaş", "Yatak",
  "Yay", "Yaz", "Yeşil", "Yıldız", "Yunanistan", "Yürek", "Yüz", "Zaman", "Zar", "Zehir"
];

export function getRandomWords(count: number): string[] {
  const shuffled = [...turkishWords].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, count);
}
